name: pinterest
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.1
  transparent_image: ^2.0.0
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/

#
#  fonts:
#    - family: RedHatDisplay
#      fonts:
#        - asset: fonts/RedHatDisplay-Bold.ttf
#        - asset: fonts/RedHatDisplay-Medium.ttf
#        - asset: fonts/RedHatDisplay-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
